### ISSUE TITLE
Output Classes

### ISSUE THREAD

**Issue by Fishhao123** [liorsidi/ViolenceDetection_CNNLSTM#10]
Hi, thanks for the code. However, I got few questions.
Why your output class is only one but not two classes? (V or not V)
And I also check the model offered in the paper you listed, they output 2 classes.
Is there any special reason?

**Comment by liorsidi** [comment]
@Fishhao123  - great question, because this is a binary problem (violence/non-violence) we can use only one output with binary cross-entropy loss, I choose this approach to simplify the network.
