### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by KillerSH** [liorsidi/ViolenceDetection_CNNLSTM#3]
Hello!
Could you provide a link to one of your datasets? The location to it should be data/raw_videos/dataset?
This project just learn to detect? How do I use the results to actually detect violence in a video?

**Comment by GxunZHANG** [comment]
> Hello!
> Could you provide a link to one of your datasets? The location to it should be data/raw_videos/dataset?
> This project just learn to detect? How do I use the results to actually detect violence in a video?

I am also looking forward to the datasets, could u pls share the link? thanks

**Comment by liorsidi** [comment]
Hi @GxunZHANG  and @KillerSH,

Sorry for the late response and thank you for raising this issue.
I Just added links for the dataset in the readme file, 
Check also the report in the git and the reference [3] to get more specific info on the data.

Good luck!

**Comment by arianaa30** [comment]
Does anyone know what to put under `raw_videos` path? Should it be only fight videos? What about non-fight videos?
