### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by arianaa30** [liorsidi/ViolenceDetection_CNNLSTM#5]
Interesting work. I was trying to test the code. I downloaded the datasets, and created the paths. But 2 of the datasets have violent and non-violent videos, while the first dataset has only fight videos. Some also have the csv files.

So what should I put in the `raw_videos` path?

**Comment by arianaa30** [comment]
Should we separate fights and non-fights videos anywhere?

**Comment by liorsidi** [comment]
@arianaa30 each dataset has different labeling logic, take a look at the DatasetBuilder.py the createDataset function.

https://github.com/liorsidi/ViolenceDetection_CNNLSTM/blob/ac33efa14046ae51b8939dbfd9631632d9befe83/DatasetBuilder.py#L53
