### ISSUE TITLE
output file?

### ISSUE THREAD

**Issue by arianaa30** [liorsidi/ViolenceDetection_CNNLSTM#7]
Hi,
What should be the expected output from `run.py`? Should we get a trained model also?
I had it running...after 15 hours the only file generated was a long-name `**_hocky_**_training_results.csv` under /results. It stopped after Epoch #9 though.

**Comment by liorsidi** [comment]
@arianaa30 the output of the results and the model itself should be at the result folder, please notice that you need to wait until the process finishes.
