### ISSUE TITLE
Some issues about the performance

### ISSUE THREAD

**Issue by pangwenfeng** [liorsidi/ViolenceDetection_CNNLSTM#8]
First of all, thanks for your work. I find that the performances of your experiments are much lower than the results described in the original paper, and the result of the first figure in your readme is not indicated which dataset belongs to. Can you explain it more? Thank you very much.

**Comment by huannguyen2008** [comment]
@pangwenfeng  hey. Can you tell me how to use this model to predict my own input video? Thanks.

**Comment by liorsidi** [comment]
@pangwenfeng please check the report at https://github.com/liorsidi/ViolenceDetection_CNNLSTM/blob/master/Report.pdf  we published, there are explanations of the figure origins (6.1 section - Hockey dataset) and reasons for the bad results on the Hockey dataset (we used a smaller amount of epochs)
